#!/bin/bash

# .vimrc

#-----------------------------------------
#Run this to install vundle and vimrc file
#-----------------------------------------
#Install Vim Env
#----------------------------------
#First get Vundle in home directory:
cd ~;
apt-get install -qq vim
yum -y install vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
cp ~/vimrc/.vimrc ~/;
vim -c 'PluginInstall' -c 'qa!'
